### ISSUE TITLE
How can I add my social media links to the website

### ISSUE THREAD

**Issue by vmandela99** [xzyaoi/hugo-hero-theme#1]
Please assist

**Comment by xzyaoi** [comment]
@vmandela99  Please refer to https://github.com/zerostaticthemes/hugo-hero-theme.

I am sorry I can not provide any further assistance, as this is just a fork of the original repository.

**Comment by vmandela99** [comment]
No problem. I figured it out. I added the in the config.toml as menu items.
Thanks though
